add yq as a dep

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -26,6 +26,13 @@ if ! [ -x "$(command -v shards)" ]; then
   exit 1
 fi
 
+# check to ensure yq is installed
+if ! [ -x "$(command -v yq)" ]; then
+  echo -e "❌ ${RED}Error${OFF}: yq is not installed"
+  echo "Please install yq -> https://github.com/mikefarah/yq"
+  exit 1
+fi
+
 compatability_warning=""
 
 # Get OS info
